### ISSUE TITLE
请问是否可以开启硬件加速？

### ISSUE THREAD

**Issue by langlangtianhq** [45kmh/image2rtsp#4]
请问可以在rk3588上开启硬件加速么，测试开启在3588上开启mpph264enc后，用于替换x264,但是推流无法正常推送。请问这个有什么解决办法吗？

**Comment by maladzenkau** [comment]
> 请问可以在rk3588上开启硬件加速么，测试开启在3588上开启mpph264enc后，用于替换x264,但是推流无法正常推送。请问这个有什么解决办法吗？

Hi, it’s possible to use any encoder that encodes a raw video stream. Since possible pipeline configurations are endless and the main purpose of this package is to convert ROS2 topics into a raw video stream, I don’t provide the functionality to automatically reconfigure the pipeline according to a chosen encoder. Just hardcode the GStreamer pipeline according to your needs, for example:
```bash
pipeline = "( appsrc name=imagesrc do-timestamp=true min-latency=0 max-latency=0 max-bytes=1000 is-live=true ! videoconvert ! videoscale !  video/x-raw, framerate = 30/1,width=640,height=480 ! x264enc bframes=0 speed-preset=veryfast key-int-max=30 bitrate=4000 ! ..."
```

**Comment by maladzenkau** [comment]
Hi, it appears there’s an issue with the [Mpph264enc](https://discuss.96boards.org/t/mpph264enc-is-too-slow/8902) encoder related to the Rockchip RK processor series. Since I don’t have this hardware and lack experience with it, I’m unable to provide support in this case.
Generally, the bottleneck is likely in the videoconvert and encoder pipeline elements. Gstreamer uses the CPU here, so essentially, it should be replaced by a GPU-accelerated format conversion plugin. For example, this is possible on a Jetson Orin NX board with ‘Gst-nvvideoconvert’ and 'NVENC' for some formats. However, as I mentioned, I don’t have a ready solution for your specific case.
